name: AntiDupe
main: zarj.antidupe.main.AntiDupe
description: ''
version: 0.0.1
website: hezar.net
author: Zarj
depend: []
api-version: 1.18

commands:
  antidupe:
    description: Main command of the plugin.
    permission: hezar.admin
    usage: /antidupe
    aliases: [ad]
